{
    "openapi": "3.0.2",
    "info": {
        "title": "BB Pay API v2",
        "version": "2.0.0",
        "description": "O sistema BB Pay do Banco do Brasil é uma solução que permite o recebimento de valores por intermédio de diversos meios de pagamento. Ao se integrar com o BB Pay, você pode habilitar diversos meios de pagamento para disponibilizá-los a um cliente (pagador), conforme a necessidade de seu negócio e da venda em questão.\n\nEsta API permite o gerenciamento e consultas de pagamentos e recebimentos de clientes PJ BB que utilizam o BB Pay.",
        "contact": {
            "name": "Banco do Brasil S.A. - BB for Developers",
            "url": "https://developers.bb.com.br"
        }
    },
    "servers": [
        {
            "url": "https://api.extranet.hm.bb.com.br/checkout/v2",
            "description": "Url de homologação sem autenticação mTLS."
        },
        {
            "url": "https://api-bbpay.hm.bb.com.br/checkout/v2/",
            "description": "Url de homologação com autenticação mTLS."
        },
        {
            "url": "https://api-bbpay.bb.com.br/checkout/v2/",
            "description": "Url de produção com autenticação mTLS."
        }
    ],
    "paths": {
        "/solicitacoes": {
            "description": "",
            "get": {
                "tags": [
                    "Solicitacoes"
                ],
                "security": [
                    {
                        "OAuth2-ClientCredentials": [
                            "checkout.solicitacoes-info"
                        ]
                    }
                ],
                "operationId": "get-solicitacoes",
                "summary": "Listar solicitações"
            },
            "post": {
                "tags": [
                    "Solicitacoes"
                ],
                "security": [
                    {
                        "OAuth2-ClientCredentials": [
                            "checkout.solicitacoes-requisicao"
                        ]
                    }
                ],
                "operationId": "post-solicitacoes",
                "summary": "Cria uma solicitação de pagamento",
                "description": ""
            }
        },
        "/pagamentos/{numeroPagamento}": {
            "get": {
                "tags": [
                    "Pagamentos"
                ],
                "security": [
                    {
                        "OAuth2-ClientCredentials": [
                            "checkout.pagamentos-info"
                        ]
                    }
                ],
                "operationId": "get-pagamento",
                "summary": "Consultar um pagamento"
            }
        },
        "/pagamentos": {
            "get": {
                "tags": [
                    "Pagamentos"
                ],
                "security": [
                    {
                        "OAuth2-ClientCredentials": [
                            "checkout.pagamentos-info"
                        ]
                    }
                ],
                "operationId": "get-pagamentos",
                "summary": "Listar pagamentos"
            }
        },
        "/devolucoes/{numeroDevolucao}": {
            "get": {
                "tags": [
                    "Devolucoes"
                ],
                "security": [
                    {
                        "OAuth2-ClientCredentials": [
                            "checkout.devolucoes-info"
                        ]
                    }
                ],
                "operationId": "get-devolucao",
                "summary": "Consultar uma devolução"
            }
        },
        "/devolucoes": {
            "get": {
                "tags": [
                    "Devolucoes"
                ],
                "security": [
                    {
                        "OAuth2-ClientCredentials": [
                            "checkout.devolucoes-info"
                        ]
                    }
                ],
                "operationId": "get-devolucoes",
                "summary": "Listar devoluções"
            },
            "post": {
                "tags": [
                    "Devolucoes"
                ],
                "security": [
                    {
                        "OAuth2-ClientCredentials": [
                            "checkout.devolucoes-requisicao"
                        ]
                    }
                ],
                "operationId": "post-devolucoes",
                "summary": "Devolver um pagamento"
            }
        },
        "/participantes": {
            "get": {
                "tags": [
                    "Participantes"
                ],
                "security": [
                    {
                        "OAuth2-ClientCredentials": [
                            "checkout.participantes-info"
                        ]
                    }
                ],
                "operationId": "get-participantes",
                "summary": "Listar participantes"
            },
            "post": {
                "tags": [
                    "Participantes"
                ],
                "security": [
                    {
                        "OAuth2-ClientCredentials": [
                            "checkout.participantes-requisicao"
                        ]
                    }
                ],
                "operationId": "post-participantes",
                "summary": "Cadastra um novo participante no split"
            }
        },
        "/participantes/{numeroParticipante}": {
            "get": {
                "tags": [
                    "Participantes"
                ],
                "security": [
                    {
                        "OAuth2-ClientCredentials": [
                            "checkout.participantes-info"
                        ]
                    }
                ],
                "operationId": "get-participante",
                "summary": "Consultar um participante"
            },
            "put": {
                "tags": [
                    "Participantes"
                ],
                "security": [
                    {
                        "OAuth2-ClientCredentials": [
                            "checkout.participantes-requisicao"
                        ]
                    }
                ],
                "operationId": "put-participante",
                "summary": "Alterar um participante",
                "description": "Altera nome e/ou dados bancários de um participante"
            },
            "delete": {
                "tags": [
                    "Participantes"
                ],
                "security": [
                    {
                        "OAuth2-ClientCredentials": [
                            "checkout.participantes-requisicao"
                        ]
                    }
                ],
                "operationId": "delete-participante",
                "summary": "Remover um participante"
            }
        },
        "/openfinance/autorizacoes": {
            "post": {
                "tags": [
                    "Openfinance"
                ],
                "security": [
                    {
                        "OAuth2-ClientCredentials": [
                            "checkout.openfinance-requisicao"
                        ]
                    }
                ],
                "operationId": "post-openfinance-autorizacao",
                "summary": "Inicia o fluxo do pagamento via Open Finance",
                "description": "Esse recurso inicia o fluxo de pagamento no Open Finance, após pagador escolher a instituição detentora da sua conta (marca). Enquanto o pagador espera o redirecionamento, esse recurso deve ser chamado para dar ciência à instituição detentora da conta do pagador de sua intenção, para que ela crie uma autorização (que será confirmada pelo pagador em ambiente de sua confiança)"
            }
        },
        "/openfinance/autorizacoes/{numeroPagamento}": {
            "get": {
                "tags": [
                    "Openfinance"
                ],
                "security": [
                    {
                        "OAuth2-ClientCredentials": [
                            "checkout.openfinance-info"
                        ]
                    }
                ],
                "operationId": "get-openfinance-autorizacao",
                "summary": "Consultar autorização",
                "description": "Esse recurso verifica se a autorização foi criada pela instituição escolhida pelo pagador e, em caso positivo, devolve a url para direcionamento do pagador ao ambiente da instituição escolhida, por ela fornecida"
            }
        },
        "/openfinance/marcas-ativas": {
            "get": {
                "tags": [
                    "Openfinance"
                ],
                "security": [
                    {
                        "OAuth2-ClientCredentials": [
                            "checkout.openfinance-info"
                        ]
                    }
                ],
                "operationId": "get-openfinance-marcas-ativas",
                "summary": "Listar marcas ativas"
            }
        },
        "/solicitacoes/{numeroSolicitacao}": {
            "get": {
                "tags": [
                    "Solicitacoes"
                ],
                "security": [
                    {
                        "OAuth2-ClientCredentials": [
                            "checkout.solicitacoes-info"
                        ]
                    }
                ],
                "operationId": "get-solicitacao",
                "summary": "Consulta uma solicitação"
            },
            "put": {
                "tags": [
                    "Solicitacoes"
                ],
                "security": [
                    {
                        "OAuth2-ClientCredentials": [
                            "checkout.solicitacoes-requisicao"
                        ]
                    }
                ],
                "operationId": "put-solicitacao",
                "summary": "Altera uma solicitação",
                "description": "Altera data de vencimento, data limite para pagamento, valor e/ou descrição de uma solicitação de pagamento, bem como o QRCode Pix e o boleto associados à solicitação. Não é possível fazer alterações em solicitações com split de valor fixo."
            },
            "delete": {
                "tags": [
                    "Solicitacoes"
                ],
                "security": [
                    {
                        "OAuth2-ClientCredentials": [
                            "checkout.solicitacoes-requisicao"
                        ]
                    }
                ],
                "operationId": "delete-solicitacao",
                "summary": "Deleta uma solicitação"
            }
        }
    },
    "components": {
        "securitySchemes": {
            "OAuth2-ClientCredentials-sandbox": {
                "flows": {
                    "clientCredentials": {
                        "tokenUrl": "https://oauth.hm.bb.com.br/oauth/token",
                        "refreshUrl": "https://oauth.hm.bb.com.br/oauth/token",
                        "scopes": {
                            "checkout.solicitacoes-info": "",
                            "checkout.solicitacoes-requisicao": "",
                            "checkout.pagamentos-info": "",
                            "checkout.pagamentos-requisicao": "",
                            "checkout.devolucoes-info": "",
                            "checkout.devolucoes-requisicao": "",
                            "checkout.participantes-info": "",
                            "checkout.participantes-requisicao": "",
                            "checkout.openfinance-info": "",
                            "checkout.openfinance-requisicao": ""
                        }
                    }
                },
                "type": "oauth2",
                "description": "Com a proteção de credenciais de usuários, o OAuth 2.0 permite a recuperação segura de recursos seguros.\nOpção para ambiente de teste/sandbox."
            },
            "OAuth2-ClientCredentials": {
                "flows": {
                    "clientCredentials": {
                        "tokenUrl": "https://oauth.bb.com.br/oauth/token",
                        "refreshUrl": "https://oauth.bb.com.br/oauth/token",
                        "scopes": {
                            "checkout.solicitacoes-info": "",
                            "checkout.solicitacoes-requisicao": "",
                            "checkout.pagamentos-info": "",
                            "checkout.pagamentos-requisicao": "",
                            "checkout.devolucoes-info": "",
                            "checkout.devolucoes-requisicao": "",
                            "checkout.participantes-info": "",
                            "checkout.participantes-requisicao": "",
                            "checkout.openfinance-info": "",
                            "checkout.openfinance-requisicao": ""
                        }
                    }
                },
                "type": "oauth2",
                "description": "Com a proteção de credenciais de usuários, o OAuth 2.0 permite a recuperação segura de recursos seguros."
            }
        }
    },
    "tags": [
        {
            "name": "Solicitacoes"
        },
        {
            "name": "Pagamentos",
            "description": ""
        },
        {
            "name": "Devolucoes",
            "description": ""
        },
        {
            "name": "Participantes",
            "description": ""
        },
        {
            "name": "Openfinance",
            "description": ""
        }
    ]
}